### ISSUE TITLE
mt7915 - WFD (wireless display) does not work

### ISSUE THREAD

**Issue by lukasz1992** [rany2/mt76#1]
Hello,

Devices connected to my router (mt7915 dbdc) can not negotiate connection to share display over Wifi.
This works with OEM driver.

I wonder if porting this patch: https://github.com/rany2/mt76/commit/46f28e7574ead4e8914cdd3a30509b43b1081c07 to mt7915 driver could solve the issue, but I do not actually understand:

1) mt7915/init.c does not have P2P mode defined in ieee80211_iface_limit and 'iw phy' confirms it
```
valid interface combinations:
                 #{ IBSS } <= 1, #{ AP, mesh point } <= 16, #{ managed } <= 19,
                 total <= 19, #channels <= 1, STA/AP BI must match, radar detect widths: { 20 MHz (no HT), 20 MHz, 40 MHz, 80 MHz, 160 MHz }

```
2) but iw phy shows also this:
```
        Supported interface modes:
                * IBSS
                * managed
                * AP
                * AP/VLAN
                * monitor
                * mesh point
                * P2P-client
                * P2P-GO
```

I wonder if any additional switches in hostapd are needed to make WFD work. I do not have any other mediatek device to test it.

I also wonder if mt7915 (from TP-Link) supports native CONNECTION_P2P_GC and CONNECTION_P2P_GO or we need to use CONNECTION_INFRA_STA and CONNECTION_INFRA_AP (like mt7921)? Is there any way to check it?

**Comment by rany2** [comment]
I'll try to backport it from OEM driver.

**Comment by rany2** [comment]
Actually I do not understand why you think that commit would make WFD work?

**Comment by rany2** [comment]
mt7915 is in AP mode, right?

**Comment by rany2** [comment]
@lukasz1992 Just had a look at it, the reason `iw phy` showed `P2P-client` , `P2P-GO` and ADHOC is because the driver does not set interface_modes; causing it to use the incorrect variant in mac80211.c

**Comment by lukasz1992** [comment]
Yes, AP mode. I am not sure if WFD depends on this or on something other.
Gonna test it on Thursday or Monday, thanks!

**Comment by rany2** [comment]
I don't think that's the issue, it's probably something else.

**Comment by lukasz1992** [comment]
Yeah, on my TV WFD actually works only when both devices are on 2.4GHz.
